export const routes = {
  home: "/",
  about: "/about",
  blog: "/blog",
  docs: "/fe-docs",
  useCases: "/use-cases",
  careers: "/careers",
  community: "/community",
  contact: "/contact",
  howItWorks: "/how-it-works",
  helperCenter: "/help-center",
  faqs: "/faqs",
  pricing: "/pricing",
  privacy: "/privacy-policy",
  termsCondition: "/terms-and-conditions",
  termsService: "/terms-of-service",
  settings: "/settings",
  podcastUpload: "/podcast/upload",
  podcastCustomize: "/podcast/customize",
  podcastDownload: "/podcast/download",
  podcastCharacters: "/podcast/characters",
  scenery: "/avatar/scenery",
}

export const links = [
  { name: "Home", link: routes.home },
  { name: "About Us", link: routes.about },
  { name: "Use cases", link: routes.useCases },
  { name: "Contact", link: routes.contact },
  { name: "How it work", link: routes.howItWorks },
]
