name: Deploy to dev server
on:
  push:
    branches: [dev]
jobs:

  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        script: whoami
